// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thxywexgqmyuqxrfsbtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeHl3ZXhncW15dXF4cmZzYnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MjU0MjcsImV4cCI6MjA1MTEwMTQyN30.5PkRssOdPM4reYwj_LiYPWIdJVGiyWDUBpnQMnsl5Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);